// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // For Supabase: DIRECT_URL for migrations, DATABASE_URL (pooler) for queries
    // Prisma CLI operations (db push, migrate) need direct connection
    url: env("DIRECT_URL") || env("DATABASE_URL"),
  },
});
