// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// For migrations, Prisma needs a direct connection (not pooler)
// DIRECT_URL is set in .env.local for local development
// For Vercel, the directUrl is configured in schema.prisma
const directUrl = env("DIRECT_URL");
const poolerUrl = env("DATABASE_URL");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct connection for schema operations (migrations, db push)
    // This is required because PgBouncer in transaction mode doesn't support DDL
    url: directUrl || poolerUrl,
  },
});
